services:
  postgres:
    image: postgres:16
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgressql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    
  redis:
    image: redis:7-alpine
    container_name: crm_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    
  bot:
    build: .
    container_name: crm_bot
    restart: always
    command: python app/main.py
    env_file:
     - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  
  celery_worker:
    build: .
    container_name: crm_celery_worker
    restart: always
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  
  celery_beat:
    build: .
    container_name: crm_celery_beat
    restart: always
    command: celery -A app.core.celery_app.celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - redis


volumes:
  pg_data: